version: "3.3"

volumes:
  postgres_data: {}

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    environment:
      RACK_ENV: production
      RAILS_ENV: production
      GOBBLEDYGOOK_DATABASE_USERNAME: postgres
      GOBBLEDYGOOK_DATABASE_PASSWORD: replace_me
      SENDGRID_API_KEY: replace_me
      RAILS_LOG_TO_STDOUT: 'yes'
      RAILS_SERVE_STATIC_FILES: 'yes'
    image: bueti/gobbledygook:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db