version: "3.9"
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    image: bueti/gobbledygook_${BUILD}
    build:
      context: .
      target: app-${BUILD}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
