version: "3.3"

volumes:
  postgres_data: {}

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    environment:
      RACK_ENV: production
      RAILS_ENV: production
      GOBBLEDYGOOK_DATABASE_USERNAME: postgres
      GOBBLEDYGOOK_DATABASE_PASSWORD: ${GOBBLEDYGOOK_DATABASE_PASSWORD}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      RAILS_LOG_TO_STDOUT: 'yes'
      RAILS_SERVE_STATIC_FILES: 'yes'
    image: bueti/gobbledygook_prod:latest
    ports:
      - "3000:3000"
    depends_on:
      - db